# Getting started
Basics of Julia programming language. 

## Printing a string
We can use `println()` to print variables

In [3]:
println("Hello World")

Hello World


## How to assign variables
All we need is a variable name, value, and an equal's sign! Julia is dynamically typed.

In [5]:
my_answer = 42
typeof(my_answer)

Int64

In [6]:
my_pi = 3.14159
typeof(my_pi)

Float64

In [7]:
😸 = "smiley cat!"
typeof(😸)

String

To type a smiley cat, use tab competion to select the emoji name and then tab again.

In [ ]:
# \:smi + <tab> --> select with down arrow + <enter> ---> <tab> + <enter> to complete

After assigning a value to a variable, we can reassign a value of a different type to that variable without any issue.

In [8]:
😸 = 1
typeof(😸)

Int64

## How to comment

In [9]:
# You can leave comments on a single line using the pound/hash key

In [10]:
#=

For multi-line comments
use the '#= =#' sequence.

=#

## Syntax for basic math

In [11]:
sum = 3 + 7

10

In [1]:
difference = 10 - 3

7

In [2]:
product = 20 * 5

100

In [3]:
power = 10 ^ 2

100

In [4]:
modulus = 101 % 2

1

In [6]:
days = 365

365

In [7]:
@assert days == 365
@assert days_float = 365.0

LoadError: TypeError: non-boolean (Float64) used in boolean context

# Strings

In [8]:
typeof('a')

Char

In [9]:
"Here is a string"

"Here is a string"

In [10]:
'this is not a string'

LoadError: ParseError:
# Error @ ]8;;file:///Users/samthomas/Documents/Work/Projects/programming-langs/julia/In[10]#1:2\In[10]:1:2]8;;\
'this is not a string'
#└──────────────────┘ ── character literal contains multiple characters

## String Interpolation

In [12]:
name = "Sam Thomas"
println("Hello, my name is $name.")

Hello, my name is Sam Thomas.


## String concatenation

In [13]:
string("How many cats ", "are too many cats ?")

"How many cats are too many cats ?"

In [14]:
string("I don't know, but ", 10, " are too few.")

"I don't know, but 10 are too few."

In [15]:
s1 = "How many cats ";
s2 =  "are too many cats ?"

"are too many cats ?"

In [16]:
s1*s2

"How many cats are too many cats ?"

# Data structures

Types of data structures:
1. Dictionaries
2. Tuples
3. Arrays

## Dictionaries

In [17]:
myphonebook = Dict("Sam" => "235-1287", "Catherine" => "239-8866")

Dict{String, String} with 2 entries:
  "Sam"       => "235-1287"
  "Catherine" => "239-8866"

In [18]:
myphonebook["Adlin"] = "487-1275"

"487-1275"

In [19]:
myphonebook

Dict{String, String} with 3 entries:
  "Sam"       => "235-1287"
  "Catherine" => "239-8866"
  "Adlin"     => "487-1275"

In [20]:
myphonebook["Sam"]

"235-1287"

In [21]:
pop!(myphonebook, "Sam")

"235-1287"

In [22]:
myphonebook

Dict{String, String} with 2 entries:
  "Catherine" => "239-8866"
  "Adlin"     => "487-1275"

## Tuples
Tuples are ordered and immutable

In [23]:
myfavoriteanimals = ("penguins", "cats", "Dogs")

("penguins", "cats", "Dogs")

In [24]:
myfavoriteanimals[1]

"penguins"

In [25]:
myfavoriteanimals[1] = "otters"

LoadError: MethodError: no method matching setindex!(::Tuple{String, String, String}, ::String, ::Int64)

## Arrays
Arrays are mutable and ordered

In [26]:
myfriends = ["Achu", "Abel", "Tanmay"]

3-element Vector{String}:
 "Achu"
 "Abel"
 "Tanmay"

In [27]:
mix = [1, 2, .3, "sam"]

4-element Vector{Any}:
 1
 2
 0.3
  "sam"

In [28]:
mix[1]

1

In [29]:
push!(mix, 12)

5-element Vector{Any}:
  1
  2
  0.3
   "sam"
 12

In [30]:
pop!(myfriends)

"Tanmay"

In [31]:
myfriends

2-element Vector{String}:
 "Achu"
 "Abel"

In [32]:
numbers = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

In [34]:
rand(4, 3) # 4x3 Array

4×3 Matrix{Float64}:
 0.476408  0.264229   0.811749
 0.357348  0.697529   0.00691742
 0.786328  0.0536956  0.144334
 0.576455  0.386798   0.84149

In [36]:
rand(4, 3, 2) # 4x3x2 Array

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.771589  0.783896   0.706671
 0.051512  0.0280941  0.448814
 0.369735  0.856975   0.430243
 0.361974  0.0802309  0.285849

[:, :, 2] =
 0.941849   0.268754  0.0155255
 0.294559   0.487958  0.195232
 0.0497707  0.486897  0.738166
 0.68561    0.992209  0.0931025

## Loops

In [37]:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [38]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [39]:
myfriends = ["sam", "abel", "achu", "tanmay"]
for friend in myfriends
    println("Hi $friend, it's great to see you!")
end

Hi sam, it's great to see you!
Hi abel, it's great to see you!
Hi achu, it's great to see you!
Hi tanmay, it's great to see you!


Note that we can replace `in` with either `=` or `∈`.

In [40]:
for n = 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [41]:
for n ∈ 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


`for` loops to create some addtional tables, Where the value of every entry is the sum of it's row and column indices.

First, we initialize an array with zeros.

In [42]:
m, n = 5, 5
A = zeros(m, n)

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [46]:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

Syntax sugar for nested for loops.

In [47]:
B = zeros(m, n)
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

The more "Julia" way to create this addition table would have been with an _array comprehension._

In [48]:
C = [i + j for i in 1:m, j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10